services:
  postgres:
    image: postgres:16

    ports:
      - "${POSTGRES_PORT}:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - inferno-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - inferno-network

  kafka:
    image: apache/kafka:3.7.1

    container_name: inferno-kafka

    restart: unless-stopped

    ports:
      - "9092:9092"

    environment:
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    networks:
      - inferno-network
  prometheus:
    image: prom/prometheus

    container_name: inferno-prometheus

    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    networks:
      - inferno-network

  grafana:
    image: grafana/grafana

    container_name: inferno-grafana

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - prometheus

    networks:
      - inferno-network

volumes:
  postgres_data:
    driver: local

  redis-data:
    driver: local

  grafana_data:
    driver: local

networks:
  inferno-network:
